training:
  batch_size: 8
  n_epochs: 500000
  n_iters: 100001
  ngpu: 1
  snapshot_freq: 500
  algo: 'dsm'
  anneal_power: 2.0

data:

  dataset: "ImageNet128"
  image_size: 128
  channels: 3
  logit_transform: false
  random_flip: false

model:
  sigma_begin: 1
  sigma_end: 0.01
  num_classes: 10
  batch_norm: false
  ngf: 128
optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.001  
  beta1: 0.9
  amsgrad: false
